### ISSUE TITLE
Can't assign latitude and longitude dynamically

### ISSUE THREAD

**Issue by SpoonS2K** [KenWillmott/SolarPosition#3]
Could it be possible to have a way to assign latitude and longitude dynamically to an existing SolarPosition object ?

**Comment by KenWillmott** [comment]
Yes, it's a good idea but I have to think about the best implementation.

**Comment by KenWillmott** [comment]
This issue has been addressed by exposing the utility function that performs the solar calculations. You can use it directly instead of using the class that calls it. I created a branch "utility" with the changes, which I will merge soon.
