### ISSUE TITLE
SolarPositionRTC Example give following error

### ISSUE THREAD

**Issue by D0u61as** [KenWillmott/SolarPosition#5]
Arduino: 1.8.12 (Windows Store 1.8.33.0) (Windows 10), Board: "Arduino Uno"

libraries\SolarPosition-master\SolarPosition.cpp.o (symbol from plugin): In function `SolarPosition::SolarPosition(float, float)':

(.text+0x0): multiple definition of `JulianDate(int, int, int)'

sketch\solarTimeRTC.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Uno.

Any thoughts as to why the example code is not running? the two libraries are installed...
Thanks in advance

**Comment by KenWillmott** [comment]
The RTC example sketch you give compiles without any problems with this library and Arduino IDE 1.8.12 on my PC. I think you have just installed the library incorrectly.

**Comment by D0u61as** [comment]
Okay,  thanks,  I will give it another go
