### ISSUE TITLE
how to convert UTC to local time

### ISSUE THREAD

**Issue by shoaib955** [KenWillmott/SolarPosition#6]
I'm working on simple heliostat project, and I've found this library very useful. but very difficult to understand for me.
I'm using RTC (DS3231) and Arduino Uno. with the example sketch "solarTmeRTC" which is working perfectly with my lat and long.
the only issue is "I can't convert UTC to local time (+5.5)" could you please help me to get the local time 

thank you...

**Comment by KenWillmott** [comment]
First of all, I hope you realize that solar calculations require the 
time reference to remain in UTC time (in this case your RTC). If you 
want to display local times for solar positions with boards that use the 
AVR processor (including the UNO), the easiest way to get local time is 
to use a time zone library, such as Jack Christensen's:

https://github.com/JChristensen/Timezone

Again, the RTC must remain set to UTC.

Thanks,
Ken
