### ISSUE TITLE
Upper case Arduino.h

### ISSUE THREAD

**Issue by generationmake** [KenWillmott/SolarPosition#7]
Hi.

Could you please change the include for Arduino.h back to upper case? Before your latest commit it was already upper case but has changed since. See this pull request #2 

Thank you.

**Comment by KenWillmott** [comment]
Okay, not sure why that happened. Changed.

**Comment by Macintosh-Fan** [comment]
Close issue?

**Comment by KenWillmott** [comment]
Done.
